apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-configmap
data:
    leaseSeconds: "10"
    zookeeperReplicas: {{ .Values.zookeeperReplicas }}
    walBufferSize: {{ .Values.wal.bufferSize }}