apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-configmap
data:
    {{- $files := .Files }}
    {{- range tuple "a.toml" "b.toml" "c.toml" }}
    {{ . }} : |-
        {{ $files.Get . }}
    {{- end }}

